# Generated by Django 5.1.2 on 2024-12-18 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('original_file', models.FileField(blank=True, max_length=512, null=True, upload_to='pdfdata/')),
                ('converted_file', models.FileField(blank=True, max_length=512, null=True, upload_to='pdfconvert/')),
                ('text_content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('convert', models.BooleanField(default=False)),
                ('clean', models.BooleanField(default=False)),
                ('data_chinh', models.BooleanField(default=False)),
                ('download_original_file', models.URLField(blank=True, max_length=512, null=True)),
                ('download_converted_file', models.URLField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VanBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.BigIntegerField(blank=True, null=True)),
                ('ngay_ban_hanh', models.BigIntegerField()),
                ('id_api', models.IntegerField(unique=True)),
                ('so_ky_hieu', models.CharField(max_length=255)),
                ('loai_van_ban', models.CharField(max_length=100)),
                ('nguoi_tao', models.CharField(max_length=100)),
                ('trich_yeu', models.TextField()),
                ('don_vi_soan_thao', models.CharField(max_length=255)),
                ('so_van_ban', models.CharField(max_length=255)),
                ('do_mat', models.CharField(max_length=50)),
                ('do_khan', models.CharField(max_length=50)),
                ('nguoi_ky', models.CharField(max_length=255)),
                ('so_luong_data', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DieuKienTai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tai', models.BigIntegerField(blank=True, null=True)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='database.data')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='van_ban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='database.vanban'),
        ),
    ]
