# Generated by Django 5.1.2 on 2024-11-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_data_data_chinh_vanban_ngay_tao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='converted_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='pdfconvert/'),
        ),
        migrations.AlterField(
            model_name='data',
            name='original_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='pdfdata/'),
        ),
    ]
