# Generated by Django 5.1.1 on 2024-11-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_data_converted_file_alter_data_original_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieuKienTai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.BigIntegerField(blank=True, null=True)),
                ('ngay_ket_thuc', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
