# Generated by Django 5.1.1 on 2024-11-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_dieukientai'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='download_converted_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='download_original_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
