# Generated by Django 5.1.1 on 2024-11-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_data_download_converted_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='download_converted_file',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='download_original_file',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
