# Generated by Django 5.1.2 on 2024-12-13 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_data_download_converted_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dieukientai',
            old_name='ngay_bat_dau',
            new_name='ngay_tai',
        ),
        migrations.RemoveField(
            model_name='dieukientai',
            name='ngay_ket_thuc',
        ),
    ]
