# Generated by Django 5.1.1 on 2024-12-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('preview_file', models.URLField(blank=True, max_length=512, null=True)),
                ('original_file', models.FileField(blank=True, max_length=512, null=True, upload_to='nguoidung/original_file')),
                ('converted_pdf', models.FileField(blank=True, max_length=512, null=True, upload_to='nguoidung/pdf')),
                ('converted_doc', models.FileField(blank=True, max_length=512, null=True, upload_to='nguoidung/doc')),
            ],
        ),
    ]
