# Generated by Django 5.1.1 on 2024-12-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguoi_dung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='converted_doc',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='nguoidung/doc/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='converted_pdf',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='nguoidung/pdf/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='nguoidung/original_file/'),
        ),
    ]
