# Generated by Django 5.1.1 on 2024-12-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguoi_dung', '0002_alter_file_converted_doc_alter_file_converted_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
